name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      gh_pages_changed: ${{ steps.filter.outputs.gh_pages == 'true' }}
      docker_changed: ${{ steps.filter.outputs.docker == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for relevant file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            # 공통 경로 목록에 대한 앵커 정의
            # 이 키(_common_paths_def)는 필터 그룹 출력을 위해 사용되지 않음
            _common_paths_def: &common_paths_list 
              - 'lib/**'
              - 'web/**'
              - 'assets/**'
              - 'pubspec.yaml'
              - 'pubspec.lock'

            # gh_pages 필터 그룹
            # 이 그룹의 변경 여부는 steps.filter.outputs.gh_pages 로 출력됨
            gh_pages: 
              - *common_paths_list # 공통 경로 목록 참조
              - '.github/workflows/ci.yml' # 이 워크플로우 파일

            # docker 필터 그룹
            # 이 그룹의 변경 여부는 steps.filter.outputs.docker 로 출력됨
            docker: 
              - *common_paths_list # 공통 경로 목록 참조
              - 'Dockerfile'
              - '.docker/**'
              - '.github/workflows/ci.yml' # 이 워크플로우 파일

  deploy_gh_pages:
    needs: check_paths
    if: needs.check_paths.outputs.gh_pages_changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web for GH Pages
        run: |
          flutter build web --release --base-href "/cherryrecorder_client/" \
          --dart-define=APP_ENV=${{ vars.APP_ENV || 'prod' }} \
          --dart-define=WEB_MAPS_API_KEY=${{ secrets.GH_PAGES_WEB_MAPS_API_KEY }} \
          --dart-define=WEB_API_BASE_URL=${{ vars.WEB_API_BASE_URL }} \
          --dart-define=CHAT_SERVER_IP=${{ vars.CHAT_SERVER_IP }}

      - name: Fix serviceWorkerVersion in index.html
        run: |
          # 빌드된 index.html 파일 확인
          echo "Checking build/web/index.html for serviceWorkerVersion..."
          
          # 템플릿 토큰이 치환되지 않은 경우를 확인
          if grep -q '{{flutter_service_worker_version}}' build/web/index.html; then
            echo "Template token not replaced. Fixing it..."
            # 타임스탬프 생성
            TIMESTAMP=$(date +%s)
            # 템플릿 토큰을 타임스탬프로 대체
            sed -i "s/{{flutter_service_worker_version}}/$TIMESTAMP/g" build/web/index.html
            echo "Replaced template token with timestamp: $TIMESTAMP"
          else
            echo "serviceWorkerVersion already set by Flutter build."
          fi
          
          # 최종 결과 확인
          echo "Final serviceWorkerVersion line:"
          grep -n "serviceWorkerVersion" build/web/index.html | head -1

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build_and_push_docker:
    needs: check_paths
    if: needs.check_paths.outputs.docker_changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/cherryrecorder_client
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "web_maps_api_key=${{ secrets.GH_PAGES_WEB_MAPS_API_KEY }}"
          build-args: |
            APP_ENV=${{ vars.APP_ENV || 'prod' }}
            WEB_API_BASE_URL=${{ vars.WEB_API_BASE_URL }}
            CHAT_SERVER_IP=${{ vars.CHAT_SERVER_IP }}
            BASE_HREF=${{ vars.DOCKER_BASE_HREF || '/cherryrecorder_client/' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Print Docker image info
        run: |
          echo "Docker image pushed successfully!"
          echo "Image digest: ${{ steps.docker_build.outputs.digest }}"
          echo "Image tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo ""
          echo "Pull commands:"
          echo "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cherryrecorder_client:latest"
          echo "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cherryrecorder_client:main"
          echo "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cherryrecorder_client:sha-${GITHUB_SHA::7}" 