name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - k8s
  workflow_dispatch:

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      gh_pages_changed: ${{ steps.filter.outputs.gh_pages == 'true' }}
      docker_changed: ${{ steps.filter.outputs.docker == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for relevant file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            # 공통 경로 목록에 대한 앵커 정의
            # 이 키(_common_paths_def)는 필터 그룹 출력을 위해 사용되지 않음
            _common_paths_def: &common_paths_list 
              - 'lib/**'
              - 'web/**'
              - 'assets/**'
              - 'pubspec.yaml'
              - 'pubspec.lock'

            # gh_pages 필터 그룹
            # 이 그룹의 변경 여부는 steps.filter.outputs.gh_pages 로 출력됨
            gh_pages: 
              - *common_paths_list # 공통 경로 목록 참조
              - '.github/workflows/ci.yml' # 이 워크플로우 파일

            # docker 필터 그룹
            # 이 그룹의 변경 여부는 steps.filter.outputs.docker 로 출력됨
            docker: 
              - *common_paths_list # 공통 경로 목록 참조
              - 'Dockerfile'
              - '.docker/**'
              - '.github/workflows/ci.yml' # 이 워크플로우 파일

  deploy_gh_pages:
    needs: check_paths
    if: needs.check_paths.outputs.gh_pages_changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web for GH Pages
        run: |
          flutter build web --release --base-href "/cherryrecorder_client/" \
          --dart-define=APP_ENV=${{ vars.APP_ENV || 'prod' }} \
          --dart-define=WEB_MAPS_API_KEY=${{ secrets.GH_PAGES_WEB_MAPS_API_KEY }} \
          --dart-define=WEB_API_BASE_URL=${{ vars.WEB_API_BASE_URL }} \
          --dart-define=CHAT_SERVER_IP=${{ vars.CHAT_SERVER_IP }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build_and_push_docker:
    needs: check_paths
    if: needs.check_paths.outputs.docker_changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/cherryrecorder_client
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=k8s-latest,enable=${{ github.ref == 'refs/heads/k8s' }}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "web_maps_api_key=${{ secrets.GH_PAGES_WEB_MAPS_API_KEY }}"
          build-args: |
            APP_ENV=${{ vars.APP_ENV || 'prod' }}
            WEB_API_BASE_URL=${{ vars.WEB_API_BASE_URL }}
            CHAT_SERVER_IP=${{ vars.CHAT_SERVER_IP }}
            BASE_HREF=${{ vars.DOCKER_BASE_HREF || '/cherryrecorder_client/' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 