name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy_gh_pages:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web for GH Pages
        run: |
          flutter build web --release --base-href "/cherryrecorder_client/" \
          --dart-define=APP_ENV=prod \
          --dart-define=WEB_MAPS_API_KEY=${{ secrets.WEB_MAPS_API_KEY }} \
          --dart-define=WEB_API_BASE_URL=https://${{ vars.SERVER_DOMAIN }}/api \
          --dart-define=WS_URL=wss://${{ vars.SERVER_DOMAIN }}/ws

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build_and_push_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cherryrecorder_client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cherryrecorder_client:${{ github.sha }}
          build-args: |
            APP_ENV=prod
            BASE_HREF=/
            WEB_MAPS_API_KEY=${{ secrets.WEB_MAPS_API_KEY }}
            WEB_API_BASE_URL=https://${{ vars.SERVER_DOMAIN }}/api
            WS_URL=wss://${{ vars.SERVER_DOMAIN }}/ws
          cache-from: type=gha
          cache-to: type=gha,mode=max
